### ISSUE TITLE
Error test with angular.element

### ISSUE THREAD

**Issue by Jhara** [joescii/sbt-js-test#8]
I have this test:

`it('should ....', function () {
    var link = '<a href>Link</a>';
     var element = angular.element(link);
     angular.element(document.body).append(element);
     element.focus();
     expect(document.activeElement.tagName).toBe('A');
  });`

When the runs fail with error

[info]   TypeError: Cannot find function focus in object [file:/xxxx/sbt-js-test-master/test-projects/angular/target/sbt-js-test/console.html]. in file:/xxxx/sbt-js-test-master/test-projects/angular/src/test/js/sample-test.js (line 25)

element focus is not a function

**Comment by joescii** [comment]
What version of angular are you using?

Joe

**Comment by Jhara** [comment]
I cloned this project and I write the Test and the test-project\angular. But in my project I use angular version 1.5.5

**Comment by joescii** [comment]
Angular ships with jqLite which doesn't include a `focus()` function. You'll need to add jquery to your project.
